---
# file: roles/common/tasks/rhel7_family.yml
- name: (rhel7 family) runlevel check
  command: systemctl get-default
  register: runlevel
  changed_when: false

- name: (rhel7 family) set multi-user.target
  command: systemctl set-default multi-user.target
  when: runlevel.stdout == "multi-user.targt"

- name: (rhel7 family) journald.conf settings
  ini_file: >
    dest=/etc/systemd/journald.conf
    section=Journal
    option={{ item.option }}
    value={{ item.value }}
    no_extra_spaces=true
    backup=true
  with_items:
    - { option: 'Storage', value: 'persistent' }
    - { option: 'RateLimitInterval', value: '0s' }
    - { option: 'SystemMaxFileSize', value: '200M' }
    - { option: 'MaxRetentionSec', value: '100day' }
    - { option: 'MaxFileSec', value: '1day' }
  register: is_journald_setting
  notify: systemd-journald restart

- name: (rhel7 family) rsyslog.conf settings
  copy: >
    src=rsyslog.conf
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=0644
    backup=true
  register: is_rsyslog_setting
  notify: rsyslog restart

- name: (rhel7 family) check firewalld zone
  shell: firewall-cmd --get-default-zone
  register: is_firewalld_zone
  changed_when: is_firewalld_zone.stdout != 'trusted'

- name: (rhel7 family) Invalid firewall services
  shell: firewall-cmd --set-default-zone=trusted
  when: is_firewalld_zone.stdout != 'trusted'

- name: (rhel7 family) chrony packages install
  yum: name=chrony state=present
  when: ntp_server is defined

- name: (rhel7 family) chrony.conf settings
  template: >
    src=chrony.conf.j2
    dest=/etc/chrony.conf
    owner=root
    group=root
    mode=0644
    backup=true
  register: is_chrony_conf_setting
  when: ntp_server is defined
  notify:
    - chronyd restart

- name: (rhel7 family) enable chronyd services
  service: name=chronyd state=started enabled=yes
  when: ntp_server is defined

- name: backup settings
  include: backup.yml
  with_flattened:
    - "{{ is_journald_setting.results|default() }}"
    - "{{ is_rsyslog_setting }}"
    - "{{ is_chrony_conf_setting|default() }}"
  loop_control:
    loop_var: backup_item

- name: reboot after kdump setting
  include: reboot.yml
  when: is_grub_setting|changed
